import Head from "next/head"
import { Dancing_Script } from '@next/font/google'
import { useState, useEffect } from "react"
import { FaHamburger } from 'react-icons/fa'


const dancing_script = Dancing_Script({ subsets: ['latin']})

export default function Layout({ children, title, }) {


  const [isScrolling, setIsScrolling] = useState()

  useEffect(() => {
    window.addEventListener('scroll', (e) => {
    if(window.scrollY >= 60) setIsScrolling(true)
    else setIsScrolling(false)
    })
  }, [])
  
  return (
    <>
      <Head>
        <title>{title || 'Fundy'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <header className={`${isScrolling ? 'sticky bg-black/80' : 'absolute bg-black/40'} top-0 left-0 \n
         right-0 w-full px-8 py-5 flex justify-between items-center transition-all`}>
        <div className={`${dancing_script.className} text-5xl text-white capitalize`}>Fundy</div>
        <button className="text-white lg:hidden" aria-label="toggle navigation" type='button' name='toggle navigation'>
          <FaHamburger size={32} />
        </button>
      </header>
      {children}
      <footer className={` bg-black w-screen px-8 py-5 flex flex-col gap-y-2 border-t border-t-purple-300/60 justify-center items-center transition-all`}>
      <div className={`${dancing_script.className} text-3xl text-white capitalize`}>Fundy</div>
      <small className="text-white">&copy; fundy 2023</small>
      </footer>
      </div>      
    </>

  )
}